apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: vm-controller
  namespace: kube-system
  labels:
    k8s-addon: vm-controller.addons.k8s.io
    k8s-app: vm-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vm-controller
subjects:
  - kind: ServiceAccount
    name: vm-controller
    namespace: kube-system