apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: vm-controller
  namespace: kube-system
  labels:
    k8s-addon: vm-controller.addons.k8s.io
    k8s-app: vm-controller
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["vm-controller-status", "vm-controller-priority-expander"]
    verbs: ["delete","get","update","watch"]