# permissions for end users to view vmclaims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmclaim-viewer-role
rules:
- apiGroups:
  - vmcontroller.uk8s.ucloud.cn
  resources:
  - vmclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vmcontroller.uk8s.ucloud.cn
  resources:
  - vmclaims/status
  verbs:
  - get
