apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vm-controller-operator-election-rolebinding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vm-controller-operator-election-role
subjects:
- kind: ServiceAccount
  name: vm-controller-operator
  namespace: kube-system
